// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPQeZ3vDZwU42MEksoPQiHY_BzCr7MKDU',
    appId: '1:705542613105:web:f60fc2af5fc698960893d0',
    messagingSenderId: '705542613105',
    projectId: 'sendra-3dbbc',
    authDomain: 'sendra-3dbbc.firebaseapp.com',
    storageBucket: 'sendra-3dbbc.appspot.com',
    measurementId: 'G-26F4N7847Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjctprhZ-JF7RjKOlF1OQcZgFJODAyV4g',
    appId: '1:705542613105:android:e7d4034d446e3dc80893d0',
    messagingSenderId: '705542613105',
    projectId: 'sendra-3dbbc',
    storageBucket: 'sendra-3dbbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_Z6LKlNy91eJ53mO6xOnRZXpUqFkUAt8',
    appId: '1:705542613105:ios:9a6617ec025898ee0893d0',
    messagingSenderId: '705542613105',
    projectId: 'sendra-3dbbc',
    storageBucket: 'sendra-3dbbc.appspot.com',
    iosClientId: '705542613105-atukr48h3hv5otsqu4qc0an1plultjer.apps.googleusercontent.com',
    iosBundleId: 'net.appdevs.walletium',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_Z6LKlNy91eJ53mO6xOnRZXpUqFkUAt8',
    appId: '1:705542613105:ios:c08e9a28dcc2c2020893d0',
    messagingSenderId: '705542613105',
    projectId: 'sendra-3dbbc',
    storageBucket: 'sendra-3dbbc.appspot.com',
    iosClientId: '705542613105-8cg3gj3245uu3ud5pt2ql58vm6c86enc.apps.googleusercontent.com',
    iosBundleId: 'net.appdevs.sendra',
  );
}
